services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    volumes:
      - backend_uploads:/app/static/uploads
      - backend_db:/app/health_passport.db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - STATIC_PROXY_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  backend_uploads:
  backend_db:
