"""LOINC data store access: CSV loading, definition promotion, alias and
multilingual lookup tables."""

import json
import logging
import os
import re
from typing import Optional

from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db.models import BiomarkerDefinition as BiomarkerDefinitionModel
from app.services.matcher.name_matching import _normalize_name

logger = logging.getLogger(__name__)

# NOTE: this module lives one directory deeper than the pre-split matcher.py,
# so data paths carry an extra ".." hop.
LOINC_CSV = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "Loinc.csv")

_loinc_row_cache: Optional[dict[str, dict]] = None


def _load_loinc_rows() -> dict[str, dict]:
    """Lazily load LOINC_NUM -> row from the full LOINC CSV (cached)."""
    global _loinc_row_cache
    if _loinc_row_cache is not None:
        return _loinc_row_cache
    import csv

    rows: dict[str, dict] = {}
    path = os.path.abspath(LOINC_CSV)
    try:
        with open(path, encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                code = (row.get("LOINC_NUM") or "").strip()
                if code:
                    rows[code] = row
    except OSError as e:
        logger.warning("Could not load LOINC CSV for promotion: %s", e)
    _loinc_row_cache = rows
    return rows


def _promote_loinc_from_csv(db: Session, code: str) -> Optional[BiomarkerDefinitionModel]:
    """Create a global BiomarkerDefinition from the full LOINC CSV for a code
    that was guessed by the LLM but not present in the seeded subset."""
    from app.db.seed_loinc import row_to_definition

    row = _load_loinc_rows().get(code)
    if not row:
        return None
    try:
        defn_dict = row_to_definition(row)
    except Exception as e:
        logger.warning("Failed to build definition for LOINC %s: %s", code, e)
        return None
    if not defn_dict.get("id"):
        return None
    new_defn = BiomarkerDefinitionModel(**defn_dict)
    # The INSERT runs inside a SAVEPOINT: a concurrent-promotion
    # IntegrityError must only discard this insert, not the caller's pending
    # work in the same transaction (ISSUES.md #40).
    nested = db.begin_nested()
    db.add(new_defn)
    try:
        db.flush()
    except IntegrityError:
        nested.rollback()
        return db.query(BiomarkerDefinitionModel).filter(
            BiomarkerDefinitionModel.id == code
        ).first()
    else:
        nested.commit()
    logger.info("Promoted LOINC %s to global definition", code)
    return new_defn


# Cache of multilingual synonym lookups (name -> loinc_code) for the request.
_loinc_alias_cache: Optional[dict[str, str]] = None
_multilingual_lookup_cache: Optional[dict[str, str]] = None
_specimen_lookup_cache: Optional[dict[str, dict[str, str]]] = None

SPECIMEN_SYNONYMS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "data", "specimen_synonyms.json"
)


def _load_loinc_aliases() -> dict[str, str]:
    """Folded-code -> survivor-code map produced by the seed's dedupe step.

    Lets a curated multilingual code that was deduplicated away still resolve to
    the surviving canonical definition instead of being promoted as a duplicate."""
    global _loinc_alias_cache
    if _loinc_alias_cache is not None:
        return _loinc_alias_cache
    path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "loinc_aliases.json")
    )
    try:
        with open(path, encoding="utf-8") as f:
            _loinc_alias_cache = json.load(f)
    except json.JSONDecodeError as e:
        logger.warning("Failed to parse loinc_aliases.json (%s); folded-code redirect disabled", e)
        _loinc_alias_cache = {}
    except OSError:
        # The file is generated by seed_loinc and committed; a missing file
        # means a broken checkout — say so instead of silently skipping the
        # folded-code -> survivor redirect (which would promote raw folded
        # codes as duplicate global definitions).
        logger.warning(
            "loinc_aliases.json not found at %s — run `python -m app.db.seed_loinc` "
            "to generate it. Folded-code alias redirects are DISABLED until then.",
            path,
        )
        _loinc_alias_cache = {}
    return _loinc_alias_cache


def _load_multilingual_lookup() -> dict[str, str]:
    """Flat (lowercased) multilingual name -> LOINC code map (parsed once,
    then memoized — the JSON never changes at runtime, ISSUES.md #60)."""
    global _multilingual_lookup_cache
    if _multilingual_lookup_cache is not None:
        return _multilingual_lookup_cache
    path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__), "..", "..", "..", "data", "multilingual_synonyms.json"
        )
    )
    if not os.path.isfile(path):
        _multilingual_lookup_cache = {}
        return _multilingual_lookup_cache
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        _multilingual_lookup_cache = {}
        return _multilingual_lookup_cache
    lookup: dict[str, str] = {}
    for mapping in data.values():
        for name, code in mapping.items():
            lookup[name.strip().lower()] = code
            # Also index a punctuation-normalized variant so OCR noise like
            # "СОЭ (по Вестергрену)" or trailing punctuation still resolves.
            lookup.setdefault(_normalize_name(name), code)
    _multilingual_lookup_cache = lookup
    return lookup


# Strips a trailing parenthetical / qualifier so noisy names like
# "СОЭ (по Вестергрену)" or "Эозинофилы, %" still hit the curated table.
_QUALIFIER_RE = re.compile(r"[\(,].*$")


def _load_specimen_lookup() -> dict[str, dict[str, str]]:
    """Specimen -> {localized name -> LOINC code} curated map.

    A generic spelling like "Глюкоза" resolves to a different target in urine
    than in serum, so specimen-specific entries are checked before the generic
    multilingual table. Parsed once and memoized (the JSON never changes at
    runtime).
    """
    global _specimen_lookup_cache
    if _specimen_lookup_cache is not None:
        return _specimen_lookup_cache
    path = os.path.abspath(SPECIMEN_SYNONYMS_PATH)
    if not os.path.isfile(path):
        _specimen_lookup_cache = {}
        return _specimen_lookup_cache
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        _specimen_lookup_cache = {}
        return _specimen_lookup_cache
    out: dict[str, dict[str, str]] = {}
    for specimen, mapping in data.items():
        if specimen.startswith("_") or not isinstance(mapping, dict):
            continue
        table: dict[str, str] = {}
        for name, code in mapping.items():
            if not name:
                continue
            table[name.strip().lower()] = code
            table.setdefault(_normalize_name(name), code)
        out[specimen.strip().lower()] = table
    _specimen_lookup_cache = out
    return out


# SYSTEM prefixes (LOINC) that identify the biomaterial of a definition.
_SPECIMEN_SYSTEM_PREFIXES = {
    "blood": ("SER", "PLAS", "BLD", "BLOOD", "PPP", "RBC", "WBC", "PLT"),
    "urine": ("URINE", "UR"),
    "feces": ("STOOL", "FECES", "FECAL"),
}


def _specimen_compatible(code: str, specimen: str) -> Optional[bool]:
    """Whether a LOINC code's SYSTEM axis fits ``specimen``.

    Returns None when the code/system/specimen is unknown (no filtering), so
    only a *known conflict* rejects a match (e.g. serum glucose for a urine
    reading)."""
    if not code or not specimen:
        return None
    row = _load_loinc_rows().get(code)
    if not row:
        return None
    system = (row.get("SYSTEM") or "").strip().upper()
    prefixes = _SPECIMEN_SYSTEM_PREFIXES.get(specimen)
    if not system or not prefixes:
        return None
    return any(system.startswith(p) for p in prefixes)


def _multilingual_code(
    name: str, multilang: dict[str, str], specimen: str = ""
) -> Optional[str]:
    """Look up a localized name in the curated tables, tolerating OCR noise.

    Specimen-specific entries win over the generic table, so a urine document's
    "Глюкоза" resolves to the urine code instead of the serum synonym."""
    if not name:
        return None
    candidates = [
        name.strip().lower(),
        _normalize_name(name),
        _normalize_name(_QUALIFIER_RE.sub("", name)),
    ]
    if specimen:
        table = _load_specimen_lookup().get(specimen) or {}
        for key in candidates:
            if key and key in table:
                return table[key]
    for key in candidates:
        if key and key in multilang:
            return multilang[key]
    return None
